export const EYE_PRESETS = [
  {
    id: 'classic',
    label: 'Classic',
    scleraRx: 44,
    scleraRy: 44,
    pupilR: 16,
    spacing: 118,
    maxOffsetScale: 1,
    brow: { style: 'soft', arch: 6, gap: 10, weight: 2 },
    lashes: { style: 'full', count: 5, length: 5 },
    pupilStyle: 'circle',
  },
  {
    id: 'beady',
    label: 'Beady',
    scleraRx: 28,
    scleraRy: 28,
    pupilR: 20,
    spacing: 88,
    maxOffsetScale: 0.7,
    brow: { style: 'flat', arch: 2, gap: 8, weight: 1.5 },
    lashes: { style: 'sparse', count: 4, length: 4 },
    pupilStyle: 'circle',
  },
  {
    id: 'wide',
    label: 'Wide',
    scleraRx: 52,
    scleraRy: 18,
    pupilR: 8,
    spacing: 132,
    maxOffsetScale: 1.1,
    brow: { style: 'flat', arch: 3, gap: 12, weight: 3 },
    lashes: { style: 'full', count: 7, length: 7 },
    pupilStyle: 'circle',
  },
  {
    id: 'sleepy',
    label: 'Sleepy',
    scleraRx: 46,
    scleraRy: 14,
    pupilR: 12,
    spacing: 110,
    maxOffsetScale: 0.8,
    brow: { style: 'droopy', arch: 5, gap: 6, weight: 1.5 },
    lashes: { style: 'sparse', count: 4, length: 4 },
    pupilStyle: 'circle',
  },
  {
    id: 'hypno',
    label: 'Hypno',
    scleraRx: 46,
    scleraRy: 46,
    pupilR: 14,
    spacing: 118,
    maxOffsetScale: 0.85,
    brow: { style: 'flat', arch: 2, gap: 11, weight: 3.5 },
    lashes: { style: 'none' },
    pupilStyle: 'ring',
  },
  {
    id: 'cyclops',
    label: 'Cyclops',
    scleraRx: 58,
    scleraRy: 58,
    pupilR: 20,
    spacing: 0,
    mono: true,
    maxOffsetScale: 1,
    brow: { style: 'surprised', arch: 8, gap: 18, weight: 4 },
    lashes: { style: 'full', count: 7, length: 6 },
    pupilStyle: 'circle',
  },
];
