export const EYE_PRESETS = [
  {
    id: 'classic',
    label: 'Classic',
    scleraRx: 50,
    scleraRy: 35,
    pupilR: 18,
    spacing: 160,
    maxOffsetScale: 1,
    brow: { style: 'soft', arch: 7, gap: 10 },
    lashes: { style: 'full', count: 7, length: 6 },
  },
  {
    id: 'beady',
    label: 'Beady',
    scleraRx: 30,
    scleraRy: 30,
    pupilR: 22,
    spacing: 95,
    maxOffsetScale: 0.7,
    brow: { style: 'flat', arch: 2, gap: 8 },
    lashes: { style: 'sparse', count: 4, length: 4 },
  },
  {
    id: 'wide',
    label: 'Wide',
    scleraRx: 65,
    scleraRy: 20,
    pupilR: 9,
    spacing: 185,
    maxOffsetScale: 1.1,
    brow: { style: 'flat', arch: 3, gap: 12 },
    lashes: { style: 'full', count: 9, length: 8 },
  },
  {
    id: 'sleepy',
    label: 'Sleepy',
    scleraRx: 54,
    scleraRy: 16,
    pupilR: 14,
    spacing: 150,
    maxOffsetScale: 0.8,
    brow: { style: 'droopy', arch: 6, gap: 6 },
    lashes: { style: 'sparse', count: 5, length: 4 },
  },
  {
    id: 'slit',
    label: 'Slit',
    scleraRx: 50,
    scleraRy: 10,
    pupilR: 6,
    spacing: 140,
    maxOffsetScale: 0.5,
    brow: { style: 'angry', arch: 5, gap: 14 },
    lashes: { style: 'none' },
  },
  {
    id: 'googly',
    label: 'Googly',
    scleraRx: 58,
    scleraRy: 58,
    pupilR: 11,
    spacing: 175,
    maxOffsetScale: 1.2,
    brow: { style: 'surprised', arch: 10, gap: 14 },
    lashes: { style: 'sparse', count: 5, length: 5 },
  },
];
